var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var alignScrollbar,appendRows,autoZoom,bottom,bottom_reached,cutSpan,data_rows,displayRows,executeAutomation,exportView,filterTable,filtered,localizePage,next_row,otherColor,prependRow,scrollDown,scrollToBottom,scrollUp,scroll_interval,setResizeAndScroll,setZoom,sortTable,startScrollDown,startScrollUp,stopScrollDown,stopScrollUp,stripeTable,top_height,zoom_factor;data_rows=[];cutSpan=function(a){return"string"!==typeof a?null!=a?a:"":a.replace(/<span[^>]*>/,"").replace("</span>","")};
sortTable=function(a){$("form").prop("disabled",!0);displayMessage("SORTING");var b={true:"ui-icon-circle-triangle-n",false:"ui-icon-circle-triangle-s"};if($("div.ui-icon",a).length){data_rows.reverse();var c=$("div.ui-icon",a).hasClass("ui-icon-circle-triangle-n");$("div.ui-icon",a).switchClass(b[c],b[!c])}else{$("#title-row div.ui-icon").remove();var d=$(a).index();if("number"===$("colgroup").children()[d--].className)data_rows.sort(function(a,b){switch(!1){case a.data[d]!==b.data[d]:return 0;case ""!==
a.data[d]:return-1;case ""!==b.data[d]:return 1;default:return parseFloat(a.data[d])-parseFloat(b.data[d])}});else if(0<$("#editor-row td").eq(d).find(".selection").length){var e=$("#editor-row td").eq(d).find(".selected").attr("id");data_rows.sort(function(a,b){if(a=a.data[d])options[e][a]||(a=cutSpan(a));if(b=b.data[d])options[e][b]||(b=cutSpan(b));return a.localeCompare(b)})}else data_rows.sort(function(a,b){a=cutSpan(a.data[d]);b=cutSpan(b.data[d]);return a.localeCompare(b)});$(a).append('<div class="ui-icon ui-icon-circle-triangle-n"></div>')}displayRows(0);
displayMessage(filtered);return $("form").prop("disabled",!1)};filtered=0;
filterTable=function(a){var b;$("form").prop("disabled",!0);displayMessage("FILTERING");var c=0;for(b=data_rows.length;c<b;c++){var d=data_rows[c];d.display=!0}if(a){var e=$("#regular").is(":checked")?function(a,b){return a.test(b)}:function(a,b){return 0<=b.toLowerCase().indexOf(a)};$("#filter-row input").each(function(a){var b;if(""!==this.value){var c=$("#regular").is(":checked")?new RegExp(this.value,"im"):this.value.toLowerCase();var f=[];var g=0;for(b=data_rows.length;g<b;g++)d=data_rows[g],
!0===d.display&&f.push(d.display=e(c,cutSpan(d.data[a]).toString().replace(/\n/g,"")));return f}});c=filtered=0;for(b=data_rows.length;c<b;c++)d=data_rows[c],filtered+=d.display}else $("#filter-row input").val(""),filtered=data_rows.length;displayRows(0);displayMessage(filtered);$("form").prop("disabled",!1);if(a&&"INPUT"!==document.activeElement.nodeName)return $(a).focus()};$("#filter-row input").on("change",function(){return filterTable(this)});
$("#filter-row input").on("keyup",function(a){if(13===a.keyCode)return a.preventDefault(),$(this).blur().focus()});$("#filter-row input").on("drop",function(a){$(this).val(a.originalEvent.dataTransfer.getData("Text"));filterTable(this);return!1});$("#filter-row input").on("mouseup",function(a){var b=this;if($(this).val())return setTimeout(function(){if(""===$(b).val())return $(b).blur().focus()})});
$("#filter-row input").on("contextmenu",function(){var a;var b=$("#filter-row input").index(this);var c={};var d=0;for(a=data_rows.length;d<a;d++){var e=data_rows[d];!0===e.display&&(c[e.data[b]]=!0)}b=$('<datalist id="filter-list"></datalist>');e=Object.keys(c).sort();c=0;for(a=e.length;c<a;c++)(d=e[c])?$(b).append("<option>"+d+"</option>"):$(b).prepend("<option>^$</option>");$(this).after(b);$(this).attr("list","filter-list");$(this).focus();return!1});
$("#filter-row input").on("input",function(a){var b=this,c;var d=$("#filter-list option").toArray();var e=[];a=0;for(c=d.length;a<c;a++){var f=d[a];$(f).val()===$(this).val()&&($(this).blur(),e.push(setTimeout(function(){return $(b).focus()})))}return e});$("#filter-row input").on("blur",function(a){$("#filter-list").remove();return $("#filter-row input").removeAttr("list")});
exportView=function(){$("form").prop("disabled",!0);return $.when(displayMessage("EXPORTING")).then(function(){var a,b,c;var d=[];$("#title-row td").each(function(a){d.push(new ActiveXObject("Scripting.Dictionary"));return d[a].Add(0,this.textContent)});var e=[];var f=1;var h=0;for(a=data_rows.length;h<a;h++){var l=data_rows[h];!0===l.display&&($.each(d,function(a,b){var c=$("<div>"+l.data[a]+"</div>").text();return 255<=c.length?(e.push({row:f+1,column:a+1,data:c}),b.Add(f,"")):b.Add(f,c)}),f++)}h=
new ActiveXObject("Excel.Application");a=h.Workbooks.Add();var k=a.ActiveSheet;a=k.Cells;a.NumberFormat="@";var g=b=0;for(c=d.length;0<=c?b<c:b>c;g=0<=c?++b:--b){var n=a(1,g+1);var m=a(d[0].Count,g+1);m=k.Range(n,m);m.Value=h.WorksheetFunction.Transpose(d[g].Items())}b=0;for(c=e.length;b<c;b++)g=e[b],a(g.row,g.column).value=g.data;a.EntireColumn.AutoFit();a.EntireRow.AutoFit();n=a(1,1);m=a(d[0].Count,d.length);k.ListObjects.Add(1,k.Range(n,m),0,1).Name="CMDB";h.Visible=!0;h.UserControl=!0;h=a=k=a=
null;setTimeout(CollectGarbage);displayMessage(filtered);return $("form").prop("disabled",!1)})};next_row=0;top_height=Math.round($("header").outerHeight(!0)+$("#head-table").outerHeight(!0));displayRows=function(a){for(next_row=0;a&&next_row<data_rows.length;)a-=data_rows[next_row++].display;for(;next_row<data_rows.length&&!data_rows[next_row].display;)next_row++;$("#data-table tbody").html("");$("html, body").scrollTop(0);appendRows();return stripeTable()};bottom=$(window).innerHeight()-top_height;
bottom_reached=!1;otherColor=function(a){return"rgb(255, 255, 255)"===$(a).css("background-color")?"lightgray":"white"};
appendRows=function(){for(var a;$("#data-table").height()<bottom&&next_row<data_rows.length;)data_rows[next_row].display&&(a=$(window.data_row),$(a).data("index",next_row),$("td",a).each(function(a){return $(this).html(data_rows[next_row].data[a])}),$("#striped").is(":checked")&&$("td",a).css("background-color",otherColor("#data-table tr:last td")),$("#data-table tbody").append(a)),next_row++;$("#data-table").height()<bottom?scrollToBottom():bottom_reached=!1;return alignScrollbar()};
scrollToBottom=function(){for(next_row=data_rows.length;$("#data-table").height()<=bottom&&prependRow(););(bottom_reached=$("#data-table").height()>bottom)&&$("html").scrollTop(Math.ceil($("body").height()*zoom_factor)-bottom);return alignScrollbar()};
prependRow=function(){var a;for(a=$("#data-table tr").length?$("#data-table tr:first").data("index"):data_rows.length;0<=--a&&!data_rows[a].display;);if(0<=a){var b=$(window.data_row);b.data("index",a);$("td",b).each(function(b){return $(this).html(data_rows[a].data[b])});$("#striped").is(":checked")&&$("td",b).css("background-color",otherColor("#data-table tr:first td"));$(b).prependTo("#data-table tbody");return!0}return!1};
stripeTable=function(){$("#data-table td").css("background-color","white");if($("#striped").is(":checked"))return $("#data-table tr:even td").css("background-color","lightgray")};$("#striped").change(stripeTable);scrollDown=function(){if(!bottom_reached){if(next_row===data_rows.length)return scrollToBottom();$("#data-table tr:first").remove();return appendRows()}};
scrollUp=function(){if(bottom_reached)$("html, body").scrollTop(0),bottom_reached=!1;else for(prependRow();$("#data-table tr:last").height()<$("#data-table").height()-bottom;)$("#data-table tr:last").remove(),next_row=$("#data-table tr:last").data("index")+1;return alignScrollbar()};$("body").mousewheel(function(a,b){return setTimeout(0<b?scrollUp:scrollDown)});$("#slider").slider({orientation:"vertical"});
alignScrollbar=function(){var a;if($("#data-table tr").length){var b=0;for(a=$("#data-table tr:first").data("index");0<=--a;)b+=data_rows[a].display;var c=0;for(a=next_row;a<data_rows.length;)c+=data_rows[a++].display;if(b+c)return $("#slider").slider("enable"),$("#slider").slider("option","max",b+c),$("#slider").slider("option","value",c);$("#slider").slider("option","value",0);return $("#slider").slider("disable")}$("#slider").slider("option","value",0);return $("#slider").slider("disable")};
$("#slider").slider({start:function(a,b){return displayMessage("SCROLLING")},stop:function(a,b){$("#slider").slider("value")?displayRows($("#slider").slider("option","max")-$("#slider").slider("value")):($("#data-table tbody").html(""),scrollToBottom());return displayMessage(filtered)}});scroll_interval=null;startScrollDown=function(a){scroll_interval=setInterval(scrollDown);return $(a).mouseout(function(){return stopScrollDown(a)})};stopScrollDown=function(a){$(a).off("mouseout");return clearInterval(scroll_interval)};
startScrollUp=function(a){scroll_interval=setInterval(scrollUp);return $(a).mouseout(function(){return stopScrollUp(a)})};stopScrollUp=function(a){$(a).off("mouseout");return clearInterval(scroll_interval)};$("form").delegate(":input","focusin",function(a){var b=$(window).scrollLeft();a=$(this).offset().left+$(this).width();var c=b+$(window).width()-55;if(a>c)return $(window).scrollLeft(b+a-c)});
setResizeAndScroll=function(){return $(window).resize(function(){bottom=$(window).innerHeight()-top_height;return bottom_reached?scrollToBottom():appendRows()}).scroll(function(){return $("#head-table").css("left",-$(this).scrollLeft())})};$("#zoom").slider({min:50,max:150,value:100,slide:function(a,b){return setZoom(b.value/100)}});zoom_factor=1;
setZoom=function(a){zoom_factor=a;$("table").css("transform","scale("+a+","+a+")");top_height=Math.round($("header").outerHeight(!0)+$("#head-table").outerHeight(!0));$("body").css("margin-top",top_height);bottom=$(window).innerHeight()-top_height;$("#zoom").slider("value",100*a);return bottom_reached?scrollToBottom():appendRows()};
autoZoom=function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:null;null==a||$(a).hasClass("off")?($("body").css("overflow-x","hidden"),$(window).scrollLeft(0).scroll(),$(window).off("resize scroll").on("resize",function(){return setZoom(($(window).width()-$("#scrollbar").width())/$("#data-table").outerWidth()*zoom_factor)}),$(a).text("Stop Zoom").switchClass("off","on").addClass("ui-state-active"),$("#zoom").slider("disable")):($("body").css("overflow-x","auto"),setZoom(1),$(window).off("resize"),
setResizeAndScroll(),$(a).text("Auto-Zoom").switchClass("on","off").removeClass("ui-state-active"),$("#zoom").slider("enable"));return $(window).resize().scroll()};
executeAutomation=function(a){$("form").prop("disabled",!0);var b=$(a).parent().parent();$("td",b).css({"border-top":"medium solid red","border-bottom":"medium solid red"});if($("#safe").is(":checked")&&!confirm($(a).attr("title")+"?"))return $("td",b).css("border","thin solid darkgray"),$("form").prop("disabled",!1);a=/[\\?&]view=([^&#]*)/.exec(location.search);a=decodeURIComponent(a[1].replace(/\+/g," "));var c=data_rows[$(b).data("index")];return $.post("/AJAX/Automation.php","automation="+encodeURIComponent(JSON.stringify([a,
c.data]))).done(function(a){try{var d=JSON.parse(a);d[1]?(data_rows.splice($.inArray(c,data_rows),1),displayRows($("#slider").slider("option","max")-$("#slider").slider("value"))):$("td",b).css("border","thin solid darkgray");return displayMessage(d[0],d[1])}catch(f){return a=f,$("td",b).css("border","thin solid darkgray"),displayMessage("JSON error: "+a.message,!0)}}).fail(function(a,b){return displayMessage("AUTOMATION error: "+b,!0)}).always(function(){return $("form").prop("disabled",!1)})};
$("table").on("mouseenter","th button",function(){return $(this).switchClass("ui-state-default","ui-state-hover")});$("table").on("mouseleave","th button",function(){return $(this).switchClass("ui-state-hover","ui-state-default")});
$("#data-table").contextmenu({delegate:"td",menu:"#contextmenu",preventContextMenuForPopup:!0,preventSelect:!1,taphold:!0,show:{effect:"slideDown",duration:0},hide:{effect:"fadeOut",duration:0},beforeOpen:function(a,b){getSelection().toString()||getSelection().selectAllChildren(b.target[0]);if($("#editor-row").length)return $("#data-table").contextmenu("enableEntry","Delete",0<window.data_row.indexOf("Delete")),a=$("#title-row button span").hasClass("ui-icon-cancel"),$("#data-table").contextmenu("enableEntry",
"Cancel",a),$("#data-table").contextmenu("enableEntry","New",!a)},select:function(a,b){var c=b.target.parent()[0];a=b.target.index()-1;switch(b.cmd){case "Copy":return document.execCommand("Copy");case "Edit":return editRow($(c).find("button")[0]);case "New":case "Cancel":return newOrCancel();case "Delete":return deleteRow($(c).find("button")[0]);case "Filter":return $("#filter-row input")[a].value=getSelection().toString(),$("#filter-row input")[a].focus(),filterTable($("#filter-row input")[a]),
getSelection().removeAllRanges();case "Sort":return $($("#title-row td")[a]).click();case "Themes":break;default:return $("#theme").attr("href","/CSS/"+b.cmd+"/jquery-ui.min.css"),$("#Themes a").each(function(){$("span",this).remove();if($(this).text()===b.cmd)return $(this).prepend('<span class="ui-icon ui-icon-check"></span>')}),$.post("/AJAX/Profile.php","theme="+b.cmd)}}});
localizePage=function(){$("[data-title]").each(function(){return $(this).prop("title",literal[$(this).attr("data-title")])});$("[data-item]").each(function(){return $(this).html($(this).html().replace(/<\/span>.*/,"</span>"+literal[$(this).attr("data-item")]))});$('[data-title="Data"]').text(literal.Data);window.data_row=window.data_row.replace(/data-title="Edit"([^<>]*)onclick/gm,'data-title="Edit" title="'+literal.Edit+'" onclick');return window.data_row=window.data_row.replace(/data-title="Delete"([^<>]*)onclick/gm,
'data-title="Delete" title="'+literal.Delete+'" onclick')};
$(document).ready(function(){$("form").prop("disabled",!0);return $.when(loadDictionary()).done(function(){localizePage();displayMessage("LOADING DATA");$("body").css("margin-top",top_height);setResizeAndScroll();return $.post("/AJAX/View.php",location.search.split("?")[1]).done(function(a){var b,c,d;try{data_rows=JSON.parse(a);var e=0;for(c=data_rows.length;e<c;e++){var f=data_rows[e];var h=f.data;var l=b=0;for(d=h.length;b<d;l=++b){var k=h[l];if(null===k||"{}"===JSON.stringify(k))f.data[l]=""}}return filterTable()}catch(g){return a=
g,displayMessage("JSON error: "+a.message,!0)}}).fail(function(a,b){return displayMessage(errorThrown,!0)}).always(function(){$(window).resize().scroll();$("#striped").prop("disabled",!1);return $("form").prop("disabled",!1)})})});//# sourceMappingURL=View.js.map
