var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var d=0,b={next:function(){if(d<a.length){var e=d++;return{value:c(e,a[e]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};
$jscomp.polyfill=function(a,c,d,b){if(c){d=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var e=a[b];e in d||(d[e]={});d=d[e]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");var createSelection,localizePage,options,resetForm;options={};
createSelection=function(a){var c=$(a).attr("id");var d=$('<input name="'+c+'" type="text" id="'+c+'-value" tabindex="-1" readonly />');var b=$('<button type="button" tabindex="-1"><span class="ui-icon ui-icon-caret-1-s"/></button>');var e=$('<datalist id="'+c+'-list"></datalist>');var g=$('<div class="selection" />');$(a).replaceWith(g).switchClass("selection","selected").attr("list",c+"-list");g.append(d).append(b).append(a).append(e);var l=function(c,b){var f;a="#"+c;d=a+"-value";e=a+"-list";var h=
options[c][b];if(b&&h)return $(d).val(h),$(a).addClass("selected").val(b);$(a).val("");$(d).val(b);if($("#regular").is(":checked")){var k=new RegExp(b,"i");h=function(a){return k.test(a)}}else k=b.toLowerCase(),h=function(a){return 0<=a.toLowerCase().indexOf(k)};b=0;for(f in options[c])b+=h(f);if(b)if($(d).css("background-color","white"),100>b)for(f in $(e).html(""),options[c])h(f)&&$(e).append('<option value="'+f.replace(/"/g,"&quot;")+'"></option>');else $(e).html('<option value="\u0001">...('+
b+literal[" options"]+")...</option>");else $(d).css("background-color","#FFAAAA");return $(a).focus()};$(b).click(function(b){return $(a).select()});$(a).focusin(function(a){$(this).css("text-align","right");if(""===$(this).val())return $(this).removeClass("selected")});$(a).focusout(function(a){return $(this).css("text-align","left")});$(a).blur(function(a){var b;if(!$(this).val()){$(this).addClass("selected");$(d).val("").css("background-color","white");if(100>(a=Object.keys(options[c]).length)){$(e).html("");
a=[];for(b in options[c])a.push($(e).append('<option value="'+b.replace(/"/g,"&quot;")+'"></option>'));return a}return $(e).html('<option value="\u0001">...('+a+literal[" options"]+")...</option>")}});$(a).on("input",function(a){if("\u0001"===$(this).val()){if(1E3>parseInt($("option",e).text().substring(4))){$(e).html("");if($("#regular").is(":checked")){var b=new RegExp($(d).val(),"i");a=function(a){return b.test(a)}}else b=$(d).val().toLowerCase(),a=function(a){return 0<=a.toLowerCase().indexOf(b)};
for(f in options[c])a(f)&&$(e).append('<option value="'+f.replace(/"/g,"&quot;")+'"></option>')}return $(this).val("").focus()}var f=options[c][$(this).val()];return $(this).val()&&f?($(d).val(f),$(this).addClass("selected")):"rgb(255, 255, 255)"===$(d).css("background-color")?($(this).hasClass("selected")&&($(this).removeClass("selected"),$(d).val("")),l(c,$(d).val()+$(this).val())):$(this).val("")});$(a).on("drop",function(b){$(d).val("");$(a).val(b.originalEvent.dataTransfer.getData("Text"));$(a).trigger("input");
$(a).focus();return!1});$(a).keydown(function(a){if(8===a.which){if(!$(this).hasClass("selected"))return a=$(d).val(),l(c,a.substr(0,a.length-1))}else if($(this).attr("required"))return $(this).removeAttr("required"),$(this).one("focusout",function(){return $(this).attr("required",!0)})});b="Table";(g=/[\\?&]table=([^&#]*)/.exec(location.search))?g=decodeURIComponent(g[1].replace(/\+/g," ")):(b="Form",g=$('[name="form-name"]').val());return $.post("/AJAX/Form.php","form_options="+encodeURIComponent(JSON.stringify({folder:b,
file:g,field:c}))).done(function(b){try{return options[c]=JSON.parse(b),$(a).blur()}catch(k){return options[c]={adathiba:"0"}}}).fail(function(a,b){return displayMessage("AJAX error: "+b,!0)})};resetForm=function(){$('form input[name="record-id"]').val("");$('form input[type!="hidden"]').val("");$("form")[0].reset();return $("form .selected").blur()};
localizePage=function(){$("[data-title]").each(function(){return $(this).prop("title",literal[$(this).attr("data-title")])});$('[data-title="Edit Data"]').text(literal["Edit Data"]);$('[data-title="Save"]').text(literal.Save);return $("#reset").text(literal["New / Reset"])};
$(document).ready(function(){$("#striped").prop("disabled",!0);$('input[type="date"]').datepicker({dateFormat:"yy-mm-dd"});$("div.ui-datepicker").css("font-size","small");$("input").on("drop",function(a){return $(this).val(a.originalEvent.dataTransfer.getData("Text"))});return $.when(loadDictionary()).done(function(){localizePage();displayMessage("LOADING OPTIONS",!1);$("input.selection").each(function(){return createSelection(this)});0<$("fieldset").length&&$("form").width(16+Math.max.apply(Math,
$("table").map(function(){return $(this).width()}).get()));$("form").submit(function(a){if("Table.php"!==location.pathname.substring(location.pathname.lastIndexOf("/")+1)){if(!1===("function"===typeof preSubmit?preSubmit():void 0)||$("#safe").is(":checked")&&!confirm(literal["SUBMIT FORM ?"]))return!1;var c=JSON.stringify($(this).serializeArray());$("form").prop("disabled",!0);var d="/AJAX/Form.php";a="form_submit=";/[\\?&]table=([^&#]*)/.exec(location.search)&&(d="/AJAX/Table.php",a="table_insert=",
c=c.replace("form-name","table-name"));$.post(d,a+encodeURIComponent(c)).done(function(a){a=JSON.parse(a);1===a.length&&(a=a[0]);try{return"function"===typeof postSubmit?postSubmit(a):a[0]?(resetForm(),displayMessage("Last Insert ID: "+(a[1].length?a[1]:"N/A"),!1)):displayMessage(a[2],!0),$("html,body").scrollTop(0)}catch(e){return a=e,displayMessage("JSON error: "+a.message,!0)}}).fail(function(a,c){return displayMessage("SAVE error: "+c,!0)}).always(function(){return $("form").prop("disabled",!1)})}return!1});
$(document).on("keydown",function(a){if(8===a.which&&!$(a.target).is("input, textarea"))return a.preventDefault()});$("form").prop("disabled",!1);displayMessage("OK");if(-1<window.navigator.userAgent.indexOf("Edge"))return $('input[type="date"]').prop("type","datum")})});//# sourceMappingURL=Form.js.map
